name: Publish Package to npmjs

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+(.beta)?'
jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3 #Setup Node
      with:
        node-version: '16.15.0'

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint
      run: |
        make lint

    - name: Build
      run: |
        make build-all

    - name: Test all
      run: |
        make test-all

    - name: Screenshot test all
      run: |
        make screenshots-all

    - name: Publish
      run: |
        npm publish ./build --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
